config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => "homes#about"

  devise_for :users

  get "search" => "searchs#search"

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get "followings" => "relationships#followings",as: "followings"
    get "followers" => "relationships#followers",as: "followers"
  end


  resources :notes, only: [:new,:index,:show,:edit,:create,:update,:destroy] do
    resources :note_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
    get "favorite" => "favorites#favorite"
  end

  resources :categories, only: [:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :notes
  belongs_to :user

  validates :name, presence: true

  def self.looks(word)
    Category.where("name LIKE?", "%#{word}%")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :category ,optional: true
  has_many :texts, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :note_comments ,dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :favorited_users , through: :favorites , source: :user

  def self.looks(word)
    Note.where("title LIKE?", "%#{word}%")
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title ,presence: true
  validates :can ,presence: true
  validates :conclude ,presence: true

  accepts_nested_attributes_for :texts, allow_destroy: true
  accepts_nested_attributes_for :references, allow_destroy: true

  enum publish_status: {
    publish: 0,
    nonpublic: 1
  }

end

app/models/note_comment.rb
class NoteComment < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :comment, presence: true
  
  enum post_status: {
    comment: 0,
    memo: 1
  }
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User"
end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :note
  has_one_attached :text_image

  validates :procedure ,presence: true
  validates :text ,presence: true

  def get_text_image(width,height)
    unless text_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      text_image.attach(io: File.open(file_path),filename: "default-image.jpg")
    end
    text_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  has_many :notes ,dependent: :destroy
  has_many :texts ,dependent: :destroy
  has_many :note_comments ,dependent: :destroy
  has_many :categories ,dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :favorited_users , through: :favorites , source: :note

  has_many :relationships , class_name: "Relationship" , foreign_key: "follower_id" , dependent: :destroy
  has_many :reverse_of_relationships , class_name: "Relationship" , foreign_key: "followed_id" , dependent: :destroy
  has_many :followings , through: :relationships , source: :followed
  has_many :followers , through: :reverse_of_relationships , source: :follower
  
  def self.looks(word)
    User.where("name LIKE?", "%#{word}%")
  end

  def followings?(user)
    followings.include?(user)
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      profile_image.attach(io: File.open(file_path),filename: "default-image.jpg")
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @notes = Note.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @notes.each do |note|
      unless Category.exists?(id: note.category_id)
        note.category_id = nil
      end
    end
  end

  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new
    @texts = @note.texts.build
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to note_path(@note)
    else
      render :new
    end
  end

  def index
    @notes = current_user.notes.all.order(created_at: :desc)
    @notes.each do |note|
      unless Category.exists?(id: note.category_id)
        note.category_id = nil
      end
    end
  end

  def show
    @comment = NoteComment.new
    @comments = NoteComment.all
    @note = Note.find(params[:id])
    unless Category.exists?(id: @note.category_id)
      @note.category_id = nil
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update(note_params)
      redirect_to note_path(@note)
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.destroy
      redirect_to notes_path
    else
      render :show
    end
  end

  private

  def note_params
    params.require(:note).permit(:title,:can,:necessities,:conclude,:category_id,:publish_status,
    texts_attributes: [:id,:procedure,:text,:text_image,:_destroy],
    references_attributes: [:id,:name,:url,:_destroy])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @category = @user.categories.new
    @categories = @user.categories.all.order(:name)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/note_comments_helper.rb
module NoteCommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<div class="container">
  <h1>ランキング</h1>
  <table class="table">
    <tr>
      <th>作成者</th>
      <th>タイトル</th>
      <th>カテゴリー</th>
      <th>いいね数</th>
      <th></th>
    </tr>
    <% @notes.each do |note| %>
      <% if note.publish_status == "publish" %>
        <tr>
          <td>
            <%= link_to user_path(note.user) ,class: "text-dark" do %>
              <%= image_tag note.user.get_profile_image(25,25) , class: "rounded-circle" %>
              <%= note.user.name %>
            <% end %>
          </td>
          <td><%= link_to note.title , note_path(note) , class: "text-dark" %></td>
          <td>
            <% if note.category_id != nil %>
              <%= note.category.name %>
            <% end %>
          </td>
          <% if user_signed_in? %>
            <td class="favorite-<%= note.id %>"><%= render "favorites/like", note: note %></td>
          <% else %>
            <td><%= note.favorites.count %></td>
          <% end %>
          <td><%= link_to "見る", note_path(note),class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/notes/_reference_fields.html.erb
<div class="nested-fields">
  参照名
  <%= f.text_field :name,class: "form-control" %><br>
  参照先url
  <%= f.text_field :url,class: "form-control" %><br>
  <%= link_to_remove_association "削除" ,f ,class: "btn btn-sm btn-danger" %>
</div>

app/views/notes/_text_fields.html.erb
<div class="nested-fields">
  <table class="table">
    <tr>
      <th class="table-dark">手順</th>
      <th class="table-dark">画像</th>
      <th class="table-dark">説明</th>
      <th class="table-dark"></th>
    </tr>
    <tr>
      <td><%= f.text_field :procedure, placeholder: "手順をここに記入" ,class: "form-control" %></td>
      <td><%= f.file_field :text_image, accept: "image/*" %></td>
      <td>
        <%= f.text_area :text,rows: 4, placeholder: "手順の詳細説明を記入" ,class: "form-control" %>
      </td>
      <td><%= link_to_remove_association "削除" ,f ,class: "btn btn-sm btn-danger" %></td>
    </tr>
  </table>
</div>

app/views/notes/edit.html.erb
<div class="container">
  <h1>ノート編集</h1>

  <%= form_with model: @note , url: note_path , method: :patch do |f| %>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "タイトル",class: "text-white" %>
        </div>
        <%= f.text_field :title ,placeholder: "タイトルを記入" ,class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "できること",class: "text-white" %>
        </div>
        <%= f.text_area :can,placeholder: "この記事を見ることで、できるようになることを記入",class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "必要なもの",class: "text-white" %>
        </div>
        <%= f.text_area :necessities , placeholder: "必要なものを記入" , class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="text-right bg-dark p-2">
          <%= link_to_add_association "手順追加",f , :texts ,data: {association_insertion_node: '#detail-association-insertion-point',association_insertion_method: 'append'}, class: "btn btn-primary rounded-circle" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-10">
        <div class="texts">
          <%= f.fields_for :texts do |t| %>
            <%= render "text_fields", f: t %>
          <% end %>
        </div>
        <div id="detail-association-insertion-point"></div>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "まとめ",class: "text-white" %>
        </div>
        <%= f.text_area :conclude, placeholder: "まとめを記入" , class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="text-right bg-dark p-2">
          <%= link_to_add_association "追加",f , :references ,data: {association_insertion_node: '#detail-association-insertion-point',association_insertion_method: 'append'}, class: "btn btn-primary rounded-circle" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-10">
        <div class="references">
          <%= f.fields_for :references do |t| %>
            <%= render "reference_fields", f: t %>
          <% end %>
        </div>
        <div id="detail-association-insertion-point"></div>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-10">
        <div class="text-center">
          <%= f.label "カテゴリー" %><br>
          <%= f.collection_select(:category_id, current_user.categories.all, :id ,:name, prompt: "カテゴリーを選択して下さい", class: "form-control") %>
        </div>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-10">
        <div class="text-center">
          <%= f.label "公開ステータス" %><br>
          <%= f.radio_button :publish_status, :publish, checked: true %>
          <%= f.label :publish_status_publish, Note.publish_statuses_i18n[:publish] %>
          <%= f.radio_button :publish_status, :nonpublic %>
          <%= f.label :publish_status_nonpublic, Note.publish_statuses_i18n[:nonpublic] %>
        </div>
      </div>
    </div>
    <div class="row my-5">
      <div class="col-10">
        <div class="text-center mt-3">
          <%= f.submit "保存", class: "btn btn-info" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/index.html.erb
<div class="container">
  <h1>ノート一覧</h1>
  <table class="table">
    <tr>
      <th>タイトル</th>
      <th>カテゴリー</th>
      <th>いいね数</th>
      <th></th>
    </tr>
    <% @notes.each do |note| %>
      <tr>
        <td><%= link_to note.title , note_path(note) , class: "text-dark" %></td>
        <td>
          <% if note.category_id != nil %>
            <%= note.category.name %>
          <% end %>
        </td>
        <td class="favorite-<%= note.id %>"><%= render "favorites/like", note: note %></td>
        <td><%= link_to "見る", note_path(note),class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/notes/new.html.erb
<div class="container">
  <h1>ノート作成</h1>

  <%= form_with model: @note , url: notes_path , method: :post do |f| %>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "タイトル",class: "text-white" %>
        </div>
        <%= f.text_field :title ,placeholder: "タイトルを記入" ,class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "できること",class: "text-white" %>
        </div>
        <%= f.text_area :can,placeholder: "この記事を見ることで、できるようになることを記入",class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "必要なもの",class: "text-white" %>
        </div>
        <%= f.text_area :necessities , placeholder: "必要なものを記入" , class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="text-right bg-dark p-2">
          <%= link_to_add_association "手順追加",f , :texts ,data: {association_insertion_node: '#detail-association-insertion-point',association_insertion_method: 'append'}, class: "btn btn-primary rounded-circle" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-10">
        <div class="texts">
          <%= f.fields_for :texts do |t| %>
            <%= render "text_fields", f: t %>
          <% end %>
        </div>
        <div id="detail-association-insertion-point"></div>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="bg-dark text-center pt-2">
          <%= f.label "まとめ",class: "text-white" %>
        </div>
        <%= f.text_area :conclude , placeholder: "まとめを記入" , class: "form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-10">
        <div class="text-right bg-dark p-2">
          <%= link_to_add_association "追加",f , :references ,data: {association_insertion_node: '#detail-association-insertion-point',association_insertion_method: 'append'}, class: "btn btn-primary rounded-circle" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-10">
        <div class="references">
          <%= f.fields_for :references do |t| %>
            <%= render "reference_fields", f: t %>
          <% end %>
        </div>
        <div id="detail-association-insertion-point"></div>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-10">
        <div class="text-center">
          <%= f.label "カテゴリー" %><br>
          <%= f.collection_select(:category_id, current_user.categories.all, :id ,:name, prompt: "カテゴリーを選択して下さい", class: "form-control") %>
        </div>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-10">
        <div class="text-center">
          <%= f.label "公開ステータス" %><br>
          <%= f.radio_button :publish_status, :publish, checked: true %>
          <%= f.label :publish_status_publish, Note.publish_statuses_i18n[:publish] %>
          <%= f.radio_button :publish_status, :nonpublic %>
          <%= f.label :publish_status_nonpublic, Note.publish_statuses_i18n[:nonpublic] %>
        </div>
      </div>
    </div>
    <div class="row my-5">
      <div class="col-10">
        <div class="text-center mt-3">
          <%= f.submit "保存", class: "btn btn-info" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row">
    <p>
      <span>作成日: <%= @note.created_at.strftime("%Y/%m/%d") %></span>
      <span class="ml-3">最終更新日: <%= @note.updated_at.strftime("%Y/%m/%d") %></span>
    </p>
    <span class="favorite-<%= @note.id %> ml-5">
      <%= render "favorites/like", note: @note %>
    </span>
    <% if current_user == @note.user %>
      <div class="mx-5">
        <p>公開ステータス:
          <% if @note.publish_status == "publish" %>
            <%= Note.publish_statuses_i18n[:publish] %>
          <% else %>
            <%= Note.publish_statuses_i18n[:nonpublic] %>
          <% end %>
        </p>
        <%= link_to "編集" , edit_note_path(@note), class: "btn btn-sm btn-success" %>
        <%= link_to "削除" , note_path(@note), method: :delete , "data-confirm" => "本当に削除しますか？" , class: "btn btn-sm btn-danger" %>
      </div>
    <% end %>
  </div>
  <% if @note.category_id != nil %>
    <p><%= @note.category.name %></p>
  <% end %>
  <h1><%= @note.title %></h1>
  <h3>できるようになること</h3>
  <p><%= safe_join(@note.can.split("\n"),tag(:br)) %></p>
  <% if @note.necessities != "" %>
    <h3>必要なもの</h3>
    <p><%= safe_join(@note.necessities.split("\n"),tag(:br)) %></p>
  <% end %>
  <h3>手順</h3>
  <ol>
    <% @note.texts.each do |text| %>
      <li><%= text.procedure %></li>
    <% end %>
  </ol>
  <h3>手順説明</h3>
  <% num = 0 %>
  <% @note.texts.each do |text| %>
    <% num += 1 %>
    <h4><%= "#{num}. #{text.procedure}" %></h4>
    <% if text.text_image.attached? %>
      <p class="text-center"><%= image_tag text.get_text_image(700,500) %></p>
    <% end %>
    <p class="mb-3"><%= safe_join(text.text.split("\n"),tag(:br)) %></p>
  <% end %>

  <h3>まとめ</h3>
  <p><%= safe_join(@note.conclude.split("\n"),tag(:br)) %></p>

<% @note.references.each do |reference| %>
  <%= link_to reference.name , "#{reference.url}" %>
<% end %>

  <div class="row">
    <div class="text-center">
      <%= render "note_comments/form", note: @note, comment: @comment %>
    </div>
  </div>
  <div class="row">
    <div class="comments-index text-center">
      <%= render "note_comments/index", note: @note %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1>ユーザー編集</h1>

  <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
    <div class="row">
      <%= f.label "名前" %><br>
      <%= f.text_field :name ,class: "form-control" %>
    </div>
    <div class="row">
      <%= f.label "画像" %>
      <%= f.file_field :profile_image, accept: "image/*" %>
    </div>
    <div class="row">
      <%= f.label "自己紹介" %><br>
      <%= f.text_area :introduction ,class: "form-control" %>
    </div>
    <div class="row">
      <%= f.submit "編集", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-7">
      <h1>ユーザー一覧</h1>
    </div>

    <div class="col-3">
      <%= render "searchs/search" %>
    </div>
  </div>

  <table class="table">
    <tr>
      <th>ユーザー名</th>
      <th>フォロー数</th>
      <th>フォロワー数</th>
      <th></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) , class: "text-dark" do %>
            <%= image_tag user.get_profile_image(50,50), class: "rounded-circle" %>
            <%= user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to user_followings_path(user),class: "text-dark" do %>
            フォロー数: <%= user.followings.count %>
          <% end %>
        </td>
        <td>
          <%= link_to user_followers_path(user),class: "text-dark" do %>
            フォロワー数:<%= user.followers.count %>
          <% end %>
        </td>
        <td><%= link_to "詳細", user_path(user), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <h1><%= image_tag @user.get_profile_image(50,50),class: "rounded-circle mb-2 mr-2" %><%= @user.name %></h1>
    </div>
    <div class="col-5">
      <%= link_to "ユーザー一覧" , users_path ,class: "btn btn-primary" %>

      <% if @user != current_user %>
        <% if current_user.followings?(@user) %>
          <%= link_to "フォローを外す" , user_relationships_path(@user) , method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "フォローする" , user_relationships_path(@user) , method: :post, class: "btn btn-info" %>
        <% end %>
      <% else %>
        <%= link_to "編集" , edit_user_path(@user), class: "btn btn-success" %>
        <%= link_to "お気に入り" , note_favorite_path(@user), class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
  <% if @user.introduction != nil %>
    <div class="row">
      <div class="col-5">
        <h3>プロフィール</h3>
        <%= safe_join(@user.introduction.split("\n"), tag(:br)) %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <%= link_to user_followings_path(@user) , class: "text-dark" do %>
      <small class="mx-3">フォロー数:<%= @user.followings.count %></small>
    <% end %>
    <%= link_to user_followers_path(@user) , class: "text-dark" do %>
      <small>フォロワー数:<%= @user.followers.count %></small>
    <% end %>
  </div>
  <h3 class="mt-5">カテゴリー</h3>
  <div class="row mb-5">
    <% if current_user == @user %>
      <%= form_with model: @category , url: categories_path, method: :post do |f| %>
        <%= f.text_field :name %>
        <%= f.submit "追加" %>
      <% end %>
    <% end %>
  </div>
  <% @categories.each do |category| %>
    <div class="row">
      <div class="col-5">
        <p><%= category.name %></p>
        <% category.notes.order(:title).each do |note| %>
          <% if (note.publish_status == "publish") || (current_user == @user) %>
            <p class="pl-3"><%= link_to note.title , note_path(note),class: "text-dark" %></p>
          <% end %>
        <% end %>
      </div>
      <div class="col-3">
        <% if current_user == @user %>
          <%= link_to "削除", category_path(category) ,method: :delete, class: "btn btn-sm btn-danger" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>