config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => "homes#about"

  devise_for :users

  get "search" => "searchs#search"

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get "followings" => "relationships#followings",as: "followings"
    get "followers" => "relationships#followers",as: "followers"
  end


  resources :notes, only: [:new,:index,:show,:edit,:create,:update,:destroy] do
    resources :note_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
    get "favorite" => "favorites#favorite"
  end

  resources :categories, only: [:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :notes
  belongs_to :user

  validates :name, presence: true

  def self.looks(word)
    Category.where("name LIKE?", "%#{word}%")
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :category ,optional: true
  has_many :texts, dependent: :destroy
  has_many :references, dependent: :destroy
  has_many :note_comments ,dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :favorited_users , through: :favorites , source: :user

  def self.looks(word)
    Note.where("title LIKE?", "%#{word}%")
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title ,presence: true
  validates :can ,presence: true
  validates :conclude ,presence: true

  accepts_nested_attributes_for :texts, allow_destroy: true
  accepts_nested_attributes_for :references, allow_destroy: true

  enum publish_status: {
    publish: 0,
    nonpublic: 1
  }

end

app/models/note_comment.rb
class NoteComment < ApplicationRecord
  belongs_to :user
  belongs_to :note

  validates :comment, presence: true
  
  enum post_status: {
    comment: 0,
    memo: 1
  }
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User"
end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :note
  has_one_attached :text_image

  validates :procedure ,presence: true
  validates :text ,presence: true

  def get_text_image(width,height)
    unless text_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      text_image.attach(io: File.open(file_path),filename: "default-image.jpg")
    end
    text_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  has_many :notes ,dependent: :destroy
  has_many :texts ,dependent: :destroy
  has_many :note_comments ,dependent: :destroy
  has_many :categories ,dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :favorited_users , through: :favorites , source: :note

  has_many :relationships , class_name: "Relationship" , foreign_key: "follower_id" , dependent: :destroy
  has_many :reverse_of_relationships , class_name: "Relationship" , foreign_key: "followed_id" , dependent: :destroy
  has_many :followings , through: :relationships , source: :followed
  has_many :followers , through: :reverse_of_relationships , source: :follower
  
  def self.looks(word)
    User.where("name LIKE?", "%#{word}%")
  end

  def followings?(user)
    followings.include?(user)
  end

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpg")
      profile_image.attach(io: File.open(file_path),filename: "default-image.jpg")
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @notes = Note.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @notes.each do |note|
      unless Category.exists?(id: note.category_id)
        note.category_id = nil
      end
    end
  end

  def about
  end
end

app/controllers/note_comments_controller.rb
class NoteCommentsController < ApplicationController
  def create
    @note = Note.find(params[:note_id])
    comment = current_user.note_comments.new(note_comment_params)
    comment.note_id = @note.id
    comment.save
  end

  def destroy
    @note = Note.find(params[:note_id])
    NoteComment.find(params[:id]).destroy
  end

  private

  def note_comment_params
    params.require(:note_comment).permit(:comment,:post_status)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new
    @texts = @note.texts.build
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to note_path(@note)
    else
      render :new
    end
  end

  def index
    @notes = current_user.notes.all.order(created_at: :desc)
    @notes.each do |note|
      unless Category.exists?(id: note.category_id)
        note.category_id = nil
      end
    end
  end

  def show
    @comment = NoteComment.new
    @comments = NoteComment.all
    @note = Note.find(params[:id])
    unless Category.exists?(id: @note.category_id)
      @note.category_id = nil
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update(note_params)
      redirect_to note_path(@note)
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.destroy
      redirect_to notes_path
    else
      render :show
    end
  end

  private

  def note_params
    params.require(:note).permit(:title,:can,:necessities,:conclude,:category_id,:publish_status,
    texts_attributes: [:id,:procedure,:text,:text_image,:_destroy],
    references_attributes: [:id,:name,:url,:_destroy])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/note_comments_helper.rb
module NoteCommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/note_comments/_form.html.erb
<%= form_with model: [@note,@comment],url:note_note_comments_path(@note,@comment),method: :post, local: false do |f| %>
  <%= f.radio_button :post_status, :comment, checked: true %>
  <%= f.label :post_status_comment, NoteComment.post_statuses_i18n[:comment] %>
  <%= f.radio_button :post_status, :memo %>
  <%= f.label :post_status_memo, NoteComment.post_statuses_i18n[:memo] %><br>
  <%= f.text_area :comment , rows: 5, class: "form-control comment-textarea" %>
  <%= f.submit "投稿", class: "btn btn-sm btn-secondary" %>
<% end %>

app/views/note_comments/_index.html.erb
<table>
  <% note.note_comments.each do |comment| %>
    <% if (comment.post_status == "comment") || (current_user == comment.user) %>
      <tr>
        <td>
          <%= link_to user_path(comment.user) do %>
            <%= image_tag comment.user.get_profile_image(25,25), class: "rounded-circle" %>
            投稿者:<%= comment.user.name %>
          <% end %>
          <br>
          <%= safe_join(comment.comment.split("\n"), tag(:br)) %>
        </td>
        <% if current_user == comment.user %>
          <td>
            <% if comment.post_status == "comment" %>
              <%= NoteComment.post_statuses_i18n[:comment] %>
            <% else %>
              <%= NoteComment.post_statuses_i18n[:memo] %>
            <% end %>
            <%= link_to "削除", note_note_comment_path(comment.note,comment),method: :delete , remote: true %>
          </td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/note_comments/create.js.erb
$(".comment-textarea").val("");
$(".comments-index").html("<%= j(render "note_comments/index", note: @note) %>");

app/views/note_comments/destroy.js.erb
$(".comments-index").html("<%= j(render "note_comments/index", note: @note) %>");